"""Runtime configuration. Everything is env-overridable so ops can tune without a deploy."""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _env(name: str, default: str) -> str:
    return os.environ.get(f"BEAMLINE_{name}", default)


def _env_int(name: str, default: int) -> int:
    return int(_env(name, str(default)))


def _env_float(name: str, default: float) -> float:
    return float(_env(name, str(default)))


@dataclass(frozen=True)
class Tier:
    """A billing tier. `burst` is the token-bucket depth, `refill` its per-second rate."""

    name: str
    monthly_bytes: int
    burst: int
    refill: float
    max_bytes_per_request: int


TIERS: dict[str, Tier] = {
    # Free keys exist so people can evaluate before paying; deliberately small.
    "free": Tier("free", monthly_bytes=1 * 1024 * 1024, burst=30, refill=0.5,
                 max_bytes_per_request=1024),
    "starter": Tier("starter", monthly_bytes=256 * 1024 * 1024, burst=120, refill=5.0,
                    max_bytes_per_request=64 * 1024),
    "pro": Tier("pro", monthly_bytes=4 * 1024 * 1024 * 1024, burst=600, refill=40.0,
                max_bytes_per_request=1024 * 1024),
    # Internal / partner keys. No monthly cap.
    "unlimited": Tier("unlimited", monthly_bytes=0, burst=5000, refill=1000.0,
                      max_bytes_per_request=8 * 1024 * 1024),
}


@dataclass(frozen=True)
class Config:
    db_path: Path = field(default_factory=lambda: Path(_env("DB", str(ROOT / "data" / "beamline.db"))))
    seed_pool_path: Path = field(
        default_factory=lambda: Path(_env("SEED_POOL", str(ROOT / "data" / "anu_seed_pool.txt")))
    )
    #: Directory holding harvested entropy shards and their index.
    pool_dir: Path = field(default_factory=lambda: Path(_env("POOL_DIR", str(ROOT / "data" / "pool"))))

    # --- Entropy sourcing -------------------------------------------------
    # ANU's public endpoint is rate-limited and unmetered-but-not-free-to-them.
    # We poll politely and lean on the local pool + OS entropy between polls.
    anu_url: str = _env("ANU_URL", "https://qrng.anu.edu.au/wp-content/plugins/colours-plugin/get_block_alpha.php")
    anu_poll_seconds: float = _env_float("ANU_POLL_SECONDS", 20.0)
    anu_api_key: str = _env("ANU_API_KEY", "")  # if set, uses the official metered API instead
    astro_poll_seconds: float = _env_float("ASTRO_POLL_SECONDS", 60.0)

    # How often the DRBG pulls fresh entropy from the pool, regardless of demand.
    reseed_seconds: float = _env_float("RESEED_SECONDS", 60.0)
    # ...and after how many generated bytes, whichever comes first.
    reseed_bytes: int = _env_int("RESEED_BYTES", 16 * 1024 * 1024)

    # --- Beacon -----------------------------------------------------------
    beacon_period_seconds: int = _env_int("BEACON_PERIOD_SECONDS", 60)

    # --- API --------------------------------------------------------------
    host: str = _env("HOST", "127.0.0.1")
    port: int = _env_int("PORT", 8080)
    admin_token: str = _env("ADMIN_TOKEN", "")  # required to mint/revoke keys over HTTP


CONFIG = Config()
